language: php

php:
  - 5.4
  - 5.5

services: mongodb

before_install:
 - cp test/testConfig.php.travis test/testConfig.php
 - composer install --dev --no-interaction --prefer-source --quiet

script:
 - ./vendor/bin/phpunit -c $PWD/test/phpunit.xml

notifications:
  email: fals e